info:
  app:
    name: eCommerce App
    description: Udacity final project
    version: 1.0.0

spring.datasource:
  driver-class-name: "org.h2.Driver"
  url: "jdbc:h2:mem:bootapp;DB_CLOSE_DELAY=-1"
  username: sa
  password:

spring.jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      dialect: "org.hibernate.dialect.H2Dialect"

spring.datasource.hikari.initializationFailTimeout: 60000

spring.mvc.throw-exception-if-no-handler-found: true

spring.resources.add-mappings: false

logging:
  level:
    root: INFO
    com.udacity: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management.endpoints:
  web:
    exposure:
      include: health,info

management.endpoints.web.cors.allowed-origins: "*"
management.endpoints.web.cors.allowed-methods: OPTIONS, GET
management.endpoints.web.cors.allowed-headers: "*"
management.endpoint.health.show-details: always


app:
  config:
    errors:
      controlleradvice: true
---
spring:
  profiles: docker

app:
  config:
    errors:
      controlleradvice: true

