version: '2.3'

services:
  jenkins:
    build: .
    privileged: true
    user: root
    ports:
      - 9000:8080
      - 50000:50000
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker